/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "udf_cache.go"

# include <stdio.h>
# include <stdlib.h>
# include <string.h>
# include <mysql.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern my_bool udf_set_cache_init(UDF_INIT* initid, UDF_ARGS* args, char* message);
extern char* udf_set_cache(UDF_INIT* initid, UDF_ARGS* args, char* result, GoUint64* length, char* null_value, char* message);
extern my_bool udf_get_cache_init(UDF_INIT* initid, UDF_ARGS* args, char* message);
extern char* udf_get_cache(UDF_INIT* initid, UDF_ARGS* args, char* result, GoUint64* length, char* null_value, char* message);
extern my_bool udf_del_cache_init(UDF_INIT* initid, UDF_ARGS* args, char* message);
extern char* udf_del_cache(UDF_INIT* initid, UDF_ARGS* args, char* result, GoUint64* length, char* null_value, char* message);
extern my_bool udf_exists_cache_init(UDF_INIT* initid, UDF_ARGS* args, char* message);
extern char* udf_exists_cache(UDF_INIT* initid, UDF_ARGS* args, char* result, GoUint64* length, char* null_value, char* message);
extern my_bool udf_ttl_cache_init(UDF_INIT* initid, UDF_ARGS* args, char* message);
extern char* udf_ttl_cache(UDF_INIT* initid, UDF_ARGS* args, char* result, GoUint64* length, char* null_value, char* message);
extern my_bool udf_count_cache_init(UDF_INIT* initid, UDF_ARGS* args, char* message);
extern char* udf_count_cache(UDF_INIT* initid, UDF_ARGS* args, char* result, GoUint64* length, char* null_value, char* message);
extern my_bool udf_list_cache_init(UDF_INIT* initid, UDF_ARGS* args, char* message);
extern char* udf_list_cache(UDF_INIT* initid, UDF_ARGS* args, char* result, GoUint64* length, char* null_value, char* message);
extern my_bool udf_list_cache_paged_init(UDF_INIT* initid, UDF_ARGS* args, char* message);
extern char* udf_list_cache_paged(UDF_INIT* initid, UDF_ARGS* args, char* result, GoUint64* length, char* null_value, char* message);
extern my_bool udf_cache_memory_init(UDF_INIT* initid, UDF_ARGS* args, char* message);
extern char* udf_cache_memory(UDF_INIT* initid, UDF_ARGS* args, char* result, GoUint64* length, char* null_value, char* message);
extern my_bool udf_cache_stat_init(UDF_INIT* initid, UDF_ARGS* args, char* message);
extern char* udf_cache_stat(UDF_INIT* initid, UDF_ARGS* args, char* result, GoUint64* length, char* null_value, char* message);
extern my_bool udf_cache_help_init(UDF_INIT* initid, UDF_ARGS* args, char* message);
extern char* udf_cache_help(UDF_INIT* initid, UDF_ARGS* args, char* result, GoUint64* length, char* null_value, char* message);

#ifdef __cplusplus
}
#endif
